<p>
	&nbsp;</p>
<p align="center" >
	<strong  >TERMS AND CONDITIONS MTV ROADIES X PREDICTIONS (&ldquo;Contest&rdquo;)</strong><br />
	<br />
</p>	
<p>
	1. This Contest is organized by Viacom 18 Media Pvt. Ltd. (hereinafter referred to as &quot;Organizers&quot;) and is open to all mobile/ landline subscribers (&ldquo;Participants&rdquo;) for participation.<br />
	2. To participate in the Contest, a Participant needs to log on to&nbsp;http://predictions.mtv.in.com&nbsp;website (&ldquo;Site&rdquo;) and click on the facebook connect link. Each Participant can register himself/ herself only once. Multiple accounts would be disqualified. The user has to be logged in through facebook to make predictions. The user makes predictions using virtual money - Roadies Dollars (R$). The user is given R$ 10,000 at the start. The user gets an additional R$ 500 every day he logs into the prediction application. The user can invest a maximum of R$ 1000 per question.</br>
	3. The following are the Prizes to be won for the Contest :<br />
	&bull; First 50 Participants on the leaderboard win Roadies X Merchandise.&nbsp;<br />
	4. All incidental costs, if any, that may arise from participating in the Contest will be borne by the Participant. The Organizers shall not be responsible in case of any network problem such as breakdown of machinery, poor network availability, disruption in the network, inconvenience/ hindrance caused, and/ or the cost of usage charged by the service provider or otherwise. Any dispute in connection to the same shall be settled between the Participant and the service provider without involving Organizers.<br />
	5. The Contest shall commence from 22th February, 2013 and shall conclude on 1st June, 2013 or on a date as decided by the Organizers (&ldquo;Contest Period&rdquo;).<br />
	6. In the event there is a tie between two participants as final winner, then the same shall be resolved through a random draw. The selection process may vary and shall be as per the Organizer&rsquo;s sole discretion. The Participants or any third party shall have no right to question the process of selection.<br />
	7. Income tax, gift tax or any other statutory taxes, duties or levies as may be applicable from time to time, arising out of free Prize/s, shall be payable by the Winner/s of the respective prize/s. In case the Winner fails to comply with the applicable law/s, the Organizers will be entitled to select another winner at their own discretion.<br />
	8. The Prize(s) shall not be transferable. No request shall be entertained by the Organizers in this behalf.<br />
	9. The Organizers shall not be responsible for the quality or deficiency etc. of the Prize/s and no claim or request, whatsoever, in this respect shall be entertained by the Organizers.<br />
	10. Employees of the Organizers and/or their associate and affiliate companies/ concerns and/ or Sponsors will not be qualified for winning any Prize/s in the Contest.<br />
	11. The Organizers reserve the right to change/ modify terms and conditions and/ or criteria of the Contest and / or the Prize for the Contest and/ or the duration/ timing of the Contest, at any time at their own discretion and without any prior notice and without assigning any reason.<br />
	12. The decision of the Organizers in connection with the Contest will be final &amp; binding and is non-contestable.<br />
	13. The winners shall be intimated by the Organizers directly. The Organizers shall not entertain any questions, correspondence, enquiries on the manner of conduct of the Contest and grant of the Prize/s from any party whatsoever.<br />
	14. Only people above 18 years can participate in this contest.<br />
	15. Apart from the entitlement to the Prize, the Winner or his/her legal heirs will have no other rights or claims against the Organizers.<br />
	16. The Participant acknowledge that he/she will not hold the Organizers and/ or any of its affiliates or agencies engaged by them with regard to this Contest liable for any loss or opportunity, monetary loss due to their participation in the Contest.<br />
	17. The Organizer is not responsible for any errors or omissions in the terms and conditions contained herein. All information provided in the Contest is provided &quot;As is&quot; without warranty of any kind. The Organizer makes no representations and disclaims all express, implied and statutory warranties of any kind to the Viewer and/or any third party including, without limitation, warranties as to accuracy, timeliness, completeness, merchantability, or fitness for any particular purpose.<br />
	18. Under no circumstance, unless due to willful misconduct or gross negligence, shall the Organizer and/or their directors, employees, officers, affiliates or subsidiaries, be liable to the Participant and/or any third party for any lost profits or lost opportunity, indirect, special, consequential, incidental, or punitive damages whatsoever, even if the Organizer has been advised of the possibility of such damages. The Participant specifically agrees not to file in person/through any family member and/or any third party any applications, criminal and/or civil proceedings in any courts or forum in India against the Organizer and/or their directors, employees, officers, affiliates or subsidiaries to claim any damages or relief in connection with the Contest.<br />
	19. The Participant grants the Organizers irrevocable consent in perpetuity to the use his/ her name, photographs, video tape taken during the prize distribution in connection with the Contest, in any and all applications including but not limited to advertising, commercials, promotion, stories, text, articles and commercial exploitation, in any and all media forms, including but not limited to radio, broadcast and television, newspapers and magazines at any time without the Participants further knowledge or consent.<br />
	20. In case of any dispute or difference in respect of this Contest, the decision of the Organizers shall be final and binding on all concerned.<br />
	21. The Contest shall be subject to jurisdiction of competent court/s at Mumbai alone.<br />
	22. Participation in this Contest implies acceptance of all the terms and conditions of the Contest. Acceptance of the Prize/s by the winner constitutes permission for Organizers, and its affiliates to shoot videos, click photographs of the Winner/s and use the Winner&#39;s name, photographs, likeness, voice and comments for advertising and promotional purposes in any media worldwide for purposes of advertising and trade without any additional compensation whatsoever.<br />
	23. It is the Participants&rsquo; responsibility to ensure that their personal details (name, address, date of birth, email id, ID Proof) are always updated and accurate in order to be able to receive the gratification/ notification in time.</p>
